services:
  # Aplicación Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: empresa_inventario_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=empresa_inventario
      - DB_USERNAME=root
      - DB_PASSWORD=root_password
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  # Servidor Web Nginx
  nginx:
    image: nginx:alpine
    container_name: empresa_inventario_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  # Base de datos MySQL
  mysql:
    image: mysql:8.0
    container_name: empresa_inventario_mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: empresa_inventario
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - laravel_network

  # Redis para cache y sesiones
  redis:
    image: redis:7-alpine
    container_name: empresa_inventario_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - laravel_network

  # phpMyAdmin para administrar la base de datos
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: empresa_inventario_phpmyadmin
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    depends_on:
      - mysql
    networks:
      - laravel_network

  # Mailtrap para desarrollo de correos
  mailtrap:
    image: axllent/mailpit
    container_name: empresa_inventario_mailtrap
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8026:8025"
    networks:
      - laravel_network

# Volúmenes para persistencia de datos
volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

# Red personalizada
networks:
  laravel_network:
    driver: bridge